package ph.edu.cibertec.veterinaria;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class Mascota {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Annotation for id Autogenerated
    Integer id;
    String name;
    String owner;
    //Holaa
}
