package ph.edu.cibertec.veterinaria.entidades;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Getter;
import lombok.Setter;

@Entity
@Setter
@Getter
public class Mascota {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Annotation for id Autogenerated
    public Long id;
    public String nombre;
    public String duenho;

    // soft delete
    Boolean estaEliminado;

}
