package ph.edu.cibertec.veterinaria.entidades;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Setter;

@Entity
@Setter
public class Mascota {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Annotation for id Autogenerated
    Integer id;
    String name;
    String owner;

    /*
     * lombok ^^^^
     * public Integer getId() {
     * return id;
     * }
     * 
     * public String getName() {
     * return name;
     * }
     * 
     * public String getOwner() {
     * return owner;
     * }
     * 
     * public void setId(Integer id) {
     * this.id = id;
     * }
     * 
     * public void setName(String name) {
     * this.name = name;
     * }
     * 
     * public void setOwner(String owner) {
     * this.owner = owner;
     * }
     */

}
